<h2> Principal Component Analysis </h2>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = {}
data["Hours"] = [9,15,25,14,10,18,0,16,5,19,16,20]
data["Marks"] = [39,56,93,61,50,75,32,85,42,70,66,80]
df = pd.DataFrame(data = data, dtype=float)
df

Hours  Marks
0     9.0   39.0
1    15.0   56.0
2    25.0   93.0
3    14.0   61.0
4    10.0   50.0
5    18.0   75.0
6     0.0   32.0
7    16.0   85.0
8     5.0   42.0
9    19.0   70.0
10   16.0   66.0
11   20.0   80.0

In [3]:
np.mean(df["Hours"])

13.916666666666666

In [4]:
def normalize(x):
    x["Hours"] = np.round((x["Hours"] - np.mean(df["Hours"],axis = 0)),decimals=2)
    x["Marks"] = np.round((x["Marks"] - np.mean(df["Marks"],axis = 0)),decimals=2)
    return x

In [5]:
normalized_df = df.copy()
normalized_df.apply(normalize, axis = 1)
normalized_df

Hours  Marks
0   -4.92 -23.42
1    1.08  -6.42
2   11.08  30.58
3    0.08  -1.42
4   -3.92 -12.42
5    4.08  12.58
6  -13.92 -30.42
7    2.08  22.58
8   -8.92 -20.42
9    5.08   7.58
10   2.08   3.58
11   6.08  17.58

In [6]:
np.matmul(np.transpose(np.array(normalized_df)),np.array(normalized_df))/(normalized_df.shape[0] - 1)

array([[ 47.71970909, 122.94698182],
       [122.94698182, 370.08334545]])

In [7]:
np.cov(df, rowvar=False)

array([[ 47.71969697, 122.9469697 ],
       [122.9469697 , 370.08333333]])

In [13]:
data1 = {}
data1["x"] = [2.5,0.5,2.2,1.9,3.1,2.3,2,1,1.5,1.1]
data1["y"] = [2.4,0.7,2.9,2.2,3.0,2.7,1.6,1.1,1.6,0.9]
df1 = pd.DataFrame(data = data1, dtype = float)
df1

x    y
0  2.5  2.4
1  0.5  0.7
2  2.2  2.9
3  1.9  2.2
4  3.1  3.0
5  2.3  2.7
6  2.0  1.6
7  1.0  1.1
8  1.5  1.6
9  1.1  0.9

In [14]:
def normalize(x):
    x["x"] = np.round((x["x"] - np.mean(df1["x"],axis = 0)),decimals=2)
    x["y"] = np.round((x["y"] - np.mean(df1["y"],axis = 0)),decimals=2)
    return x

In [16]:
normalized_df1 = df1.copy()
normalized_df1.apply(normalize,axis = 1)
normalized_df1

x     y
0  0.69  0.49
1 -1.31 -1.21
2  0.39  0.99
3  0.09  0.29
4  1.29  1.09
5  0.49  0.79
6  0.19 -0.31
7 -0.81 -0.81
8 -0.31 -0.31
9 -0.71 -1.01

In [17]:
df1_cov = np.matmul(np.transpose(np.array(normalized_df1)),np.array(normalized_df1))/(normalized_df1.shape[0] - 1)
df1_cov

array([[0.61655556, 0.61544444],
       [0.61544444, 0.71655556]])

In [18]:
np.matmul(df1_cov,np.array([-0.7351786,0.6778734]))

array([-0.03608503,  0.03327237])

In [19]:
u,s,vh = np.linalg.svd(np.array(normalized_df1))

In [21]:
u.shape

(10, 10)

In [22]:
s

array([3.3994484 , 0.66464321])

In [23]:
vh

array([[-0.6778734 , -0.73517866],
       [ 0.73517866, -0.6778734 ]])

In [28]:
np.matmul(df1_cov,np.transpose(vh[0,:]))

array([-0.87040823, -0.94398977])