In [3]:
import re
candidates = '{1 2 3 }, {1 4 5}, {1 2 4}, {1 2 5}, {1 5 9}, {1 3 6},{2 3 4}, {2 5 9},{3 4 5}, {3 5 6}, {3 5 9}, {3 8 9}, {3 2 6},{4 5 7}, {4 1 8}, {4 7 8}, {4 6 7},{6 1 3}, {6 3 4}, {6 8 9}, {6 2 1}, {6 4 3}, {6 7 9},{8 2 4}, {8 9 1}, {8 3 6}, {8 3 7}, {8 4 7}, {8 5 1}, {8 3 1}, {8 6 2}'
#candidates = '{1 4 5}, {1 2 4}, {4 5 7}, {1 2 5}, {4 5 8}, {1 5 9}, {1 3 6}, {2 3 4}, {5 6 7},{3 4 5}, {3 5 6}, {3 5 7}, {6 8 9}, {3 6 7}, {3 6 8}'
res = [int(i) for i in re.findall(r'[^{},]',candidates) if i != ' ']
interval = int(len(res)/3)
res_final = [res[3*int(i):3*int(i+1)] for i in range(0,interval)]

In [12]:
x = list()

[x.append(i) for i in list(map(sorted, res_final)) if i not in x]
len(x)
x

[[1, 2, 3],
 [1, 4, 5],
 [1, 2, 4],
 [1, 2, 5],
 [1, 5, 9],
 [1, 3, 6],
 [2, 3, 4],
 [2, 5, 9],
 [3, 4, 5],
 [3, 5, 6],
 [3, 5, 9],
 [3, 8, 9],
 [2, 3, 6],
 [4, 5, 7],
 [1, 4, 8],
 [4, 7, 8],
 [4, 6, 7],
 [3, 4, 6],
 [6, 8, 9],
 [1, 2, 6],
 [6, 7, 9],
 [2, 4, 8],
 [1, 8, 9],
 [3, 6, 8],
 [3, 7, 8],
 [1, 5, 8],
 [1, 3, 8],
 [2, 6, 8]]

In [148]:
res_final

[[1, 4, 5],
 [1, 2, 4],
 [4, 5, 7],
 [1, 2, 5],
 [4, 5, 8],
 [1, 5, 9],
 [1, 3, 6],
 [2, 3, 4],
 [5, 6, 7],
 [3, 4, 5],
 [3, 5, 6],
 [3, 5, 7],
 [6, 8, 9],
 [3, 6, 7],
 [3, 6, 8]]

In [238]:
class root:
    def __init__(self):
        self.remainderone = None
        self.remaindertwo = None
        self.remainderzero = None
        
class remainderZeroNode:
    def __init__(self):
        self.content = None
        self.remainderone = None
        self.remaindertwo = None
        self.remainderzero = None
        self.complete = False

class remainderOneNode:
    def __init__(self):
        self.content = None
        self.remainderone = None
        self.remaindertwo = None
        self.remainderzero = None
        self.complete = False

class remainderTwoNode:
    def __init__(self):
        self.content = None
        self.remainderone = None
        self.remaindertwo = None
        self.remainderzero = None
        self.complete = False

In [239]:
def create_hashtree(candidateset,node = None, sort = False, max_leafsize = 3,depth = 0):
    if sort == True:
        candidateset = [sorted(i) for i in candidateset]
    if depth == 0:
        node.remainderone = remainderOneNode()
        node.remaindertwo  = remainderTwoNode()
        node.remainderzero  = remainderZeroNode()
        node.remainderone.content = [i for i in candidateset if i[0]%3 == 1]
        node.remaindertwo.content = [i for i in candidateset if i[0]%3 == 2]
        node.remainderzero.content = [i for i in candidateset if i[0]%3 == 0]
    else:
        node.remainderone = remainderOneNode()
        node.remaindertwo  = remainderTwoNode()
        node.remainderzero  = remainderZeroNode()
        node.remainderone.content = [i for i in candidateset if i[depth]%3 == 1]
        node.remaindertwo.content = [i for i in candidateset if i[depth]%3 == 2]
        node.remainderzero.content = [i for i in candidateset if i[depth]%3 == 0]

    if (len(node.remainderone.content) > max_leafsize) & (depth < 2):
        create_hashtree(candidateset = node.remainderone.content, node = node.remainderone, depth = depth + 1)
    else:
        node.remainderone.complete = True
    if (len(node.remaindertwo.content) > max_leafsize) & (depth < 2):
        create_hashtree(candidateset = node.remaindertwo.content, node = node.remaindertwo, depth = depth + 1)
    else:
        node.remaindertwo.complete = True
    if (len(node.remainderzero.content) > max_leafsize) & (depth < 2):
        create_hashtree(candidateset = node.remainderzero.content, node = node.remainderzero, depth = depth + 1)
    else:
        node.remainderzero.complete = True

In [240]:
rootnode = root()
create_hashtree(res_final,node = rootnode, sort = False, max_leafsize = 3,depth = 0)

In [241]:
rootnode.remainderone.content

[[1, 4, 5], [1, 2, 4], [4, 5, 7], [1, 2, 5], [4, 5, 8], [1, 5, 9], [1, 3, 6]]

In [242]:
rootnode.remaindertwo.content

[[2, 3, 4], [5, 6, 7]]

In [243]:
rootnode.remainderone.remainderone.content

[[1, 4, 5]]

In [253]:
rootnode.remainderone.remaindertwo.content

[[1, 2, 4], [4, 5, 7], [1, 2, 5], [4, 5, 8], [1, 5, 9]]

In [254]:
rootnode.remainderone.remaindertwo.content

[[1, 2, 4], [4, 5, 7], [1, 2, 5], [4, 5, 8], [1, 5, 9]]

In [246]:
rootnode.remainderone.remaindertwo.remaindertwo.content

[[1, 2, 5], [4, 5, 8]]

In [247]:
rootnode.remainderone.remaindertwo.remainderzero.content

[[1, 5, 9]]

In [248]:
rootnode.remainderzero.remainderone.content

[[3, 4, 5]]

In [249]:
rootnode.remainderzero.remaindertwo.content

[[3, 5, 6], [3, 5, 7], [6, 8, 9]]

In [250]:
rootnode.remainderzero.remainderzero.content

[[3, 6, 7], [3, 6, 8]]

In [255]:
import copy
def output_hashtree(result,node = None):
    if len(result) == 0:
        for attr in node.__dict__:
            result.append(getattr(node,attr))
        output_hashtree(result,node)
    else:
        for i in range(len(result)):
            if result[i].complete == True:
                result[i] = result[i].content
            else:
                obj = copy.deepcopy(result[i])
                result[i] = list()
                for attr in list(obj.__dict__.keys())[1:-1]:
                    result[i].append(getattr(obj,attr))
                output_hashtree(result=result[i])

In [256]:
result = list()
output_hashtree(result, node = rootnode)
print(result)

[[[[1, 4, 5]], [[[1, 2, 4], [4, 5, 7]], [[1, 2, 5], [4, 5, 8]], [[1, 5, 9]]], [[1, 3, 6]]], [[2, 3, 4], [5, 6, 7]], [[[3, 4, 5]], [[3, 5, 6], [3, 5, 7], [6, 8, 9]], [[3, 6, 7], [3, 6, 8]]]]


In [ ]:
res = list()
for attr in rootnode.__dict__:
    res.append(getattr(rootnode,attr))
res

In [ ]:
res[0].remainderzero

In [ ]:
res2 = list()
for i in range(len(res)):
    for attr in res[i].__dict__:
        res2.append(getattr(attr,res[i]))


TypeError: getattr(): attribute name must be string

In [ ]:
list(res[0].__dict__.keys())[1:-1]

['remainderzero', 'remainderone', 'remaindertwo']

In [2]:
A = [1,2,3,5,6]
level = 1
n = 3

for i in range(-1*(len(A) - 1),-1*(n - level) + 1):
    print(A[i:])
    print(A[i - 1])




[2, 3, 5, 6]
1
[3, 5, 6]
2
[5, 6]
3


In [7]:
def print_candidates(A,level,candidate_size):
    if level < candidate_size:
        for i in range(-1*(len(A) - 1),-1*(candidate_size - level) + 1):
            print(A[i - 1],A[1:])
            print_candidates(A[i:],level + 1, candidate_size)
    #print(A)

print_candidates(A,level,n)

1 [2, 3, 5, 6]
2 [3, 5, 6]
3 [3, 5, 6]
5 [3, 5, 6]
2 [2, 3, 5, 6]
3 [5, 6]
5 [5, 6]
3 [2, 3, 5, 6]
5 [6]


In [8]:
33%7

5

In [24]:
a = set()
a.add("A")
a.add("B")
a.add("C")
a

{'A', 'B', 'C'}

In [22]:
set("A").issubset(a)

True

In [27]:
for i in {'B','C'}:
    a.remove(i)
a

{'A'}

In [17]:
from itertools import chain, combinations

In [20]:
list(chain.from_iterable(combinations({"E","B","A"}, r) for r in range(1, len({"E","B","A"}))))

[('E',), ('A',), ('B',), ('E', 'A'), ('E', 'B'), ('A', 'B')]

In [30]:
from collections import Counter
count1 = Counter()
count1.update([1,2,3,4,2,3,1])
count1

Counter({1: 2, 2: 2, 3: 2, 4: 1})

In [31]:
import numpy as np

conf = np.array([3/7,4/5,6/7,2/6,2/5])
interest = np.array([0.214,0.72,0.771,0.167,0.2])

mean_conf = np.mean(conf)
mean_interest = np.mean(interest)

(np.matmul((conf - mean_conf),np.transpose((interest - mean_interest))))/(len(conf)*np.std(conf)*np.std(interest))

0.9960892595090772

In [36]:
conf = np.array([3/7,4/5,6/7,2/6,2/5])
kl = np.array([-0.039,-0.063,-0.033,-0.075,-0.045])

mean_conf = np.mean(conf)
mean_kl = np.mean(kl)

(np.matmul((conf - mean_conf),np.transpose((kl - mean_kl))))/(len(conf)*np.std(conf)*np.std(kl))

0.3133486529753013

In [39]:
(np.matmul((conf - mean_conf),np.transpose((kl - mean_kl))))

0.0053714285714285695

In [40]:
np.transpose((kl - mean_kl))

array([ 0.012, -0.012,  0.018, -0.024,  0.006])

In [44]:
import scipy.stats as sp




In [45]:
sp.mstats.pearsonr(conf,kl)

(0.31334865297530134, 0.6076607404884304)

In [41]:
(kl - mean_kl)

array([ 0.012, -0.012,  0.018, -0.024,  0.006])

In [ ]:
(kl - mean_kl)

array([ 0.012, -0.012,  0.018, -0.024,  0.006])